### PR TITLE
Fix for XmlNsDefinition in referenced assemblies

### LINKED ISSUE #105: XMLNS Definitions not working on external libraries.
> This issue has been tested on Avalonia's latest nightly builds.
To repro, make a new Avalonia project, and add [AvaloniaEdit](https://www.nuget.org/packages/Avalonia.AvaloniaEdit/) package. Add the following namespace to MainWindow tag:
>```
>xmlns:ae="https://github.com/avaloniaui/avaloniaedit"
>```
>It should fail to find the type when you add the following control on MainWindow's main Grid:
>```
><ae:TextEditor/>
>```
https://github.com/AvaloniaUI/Avalonia/issues/1646

### PR DESCRIPTION
**Pull request by dmetzgar**
Fixes #105 

This seems to fix the issue in my testing. Weirdly, you would think this code does the same thing. Using reflection in this way is pretty fragile anyway.

### CODE REVIEW

**Comment by cwensley** [comment]
Hey @dmetzgar, that's great, thanks for the fix!

Not sure why the reflection is broken, but probably due to how .NET Core has implementations in various assemblies (vs. mscorlib for .NET framework/mono).  Reflection was initially used as Portable.Xaml was only targeting PCL then .NET Standard 1.x before which doesn't have access to these api's.

**Comment by dmetzgar** [comment]
@cwensley, what's your plan for next release? I'd like to cut a new version of CoreWF but I'll wait until the latest Portable.Xaml is out.

**Comment by cwensley** [comment]
@dmetzgar I was waiting to get #103 merged in before the next release, but I can just as easily make an interim release to help you move forward.  I'll work on getting it out in the next few days.

**Comment by cm4ker** [comment]
@dmetzgar Hey! I want to end #103 issue.  When I push fixes for review and I think it can be merged. Then we can bump the version.

**Comment by dmetzgar** [comment]
@cwensley and @cm4ker thanks for getting this merged. I'll do some testing and get a new version of CoreWF pointing to this hopefully this weekend.

**Pull request merged**
