### PR TITLE
Proposal for collection handling like a System.Xaml

### PR DESCRIPTION
**Pull request by cm4ker**
Hi there. Where the proposal for fixing different collection handling in portable.xaml and system.xaml.

The root of the problem:

Then the collection contains single element the system.xaml not re-assign this property (Check added test and just add the elements to the collection in the xml representation)

Portable.Xaml now working like this:

We are have collection with 1 element.
On parsing stage we add the GetObject xaml node and go through the StartGetObject in the InternalXamlObjectWriter there we read the reference of the current collection(initialized or not) after that we are save it into the ObjectState. Then we end populating the collection we are _re-assign_ it. 

I try to read specs and documentation from ms but I not found any useful information about this question, why the collection property must not reassign then the elements count = 1 and must assing then elements count > 1.

I write the fixes to make portable.xaml like a system.xaml behavour. This changes so suspect because: 
1) I'm not realize how _must_ work xaml engine
2) I not found the docs about this
3) My programmer skill not high yet.

Can anyone help and explain what direction to take?

Thanks in advice.

### CODE REVIEW

**Comment by cm4ker** [comment]
I think that we have not tests for all-cases. If any can add failing test - feel free.

**Comment by grokys** [comment]
I don't quite understand what the System.Xaml behavior is around this. Are you saying that currently Portable.Xaml works differently between collections with 1 element and collections with >1 element but System.Xaml always behaves the same?

I tried writing a test for this (on `develop` - without the fix in this PR) and I couldn't see any difference between 1 and >1 elements: Portable.Xaml always seemed to erroneously call the setter after calling the getter.

I think it would be useful to have more tests to demonstrate this.

**Comment by grokys** [comment]
Ok, from what i can see, the issue comes down to this:

```csharp
[ContentProperty(nameof(Items))]
public class CollectionAssignnmentTest
{
	List<TestClass4> items = new List<TestClass4>();

	public bool Assigned { get; private set; }

	public List<TestClass4> Items
	{
		get => items;
		set { items = value; Assigned = true; }
	}
}
```

```csharp
	[Test]
	public void CollectionShouldNotBeAssigned()
	{
		var xml = $@"
<CollectionAssignnmentTest xmlns='clr-namespace:MonoTests.Portable.Xaml;assembly=Portable.Xaml_test_net_4_0'>
    <TestClass4/>	
</CollectionAssignnmentTest>".UpdateXml();
		var result = (CollectionAssignnmentTest)XamlServices.Parse(xml);

		Assert.False(result.Assigned);
		Assert.AreEqual(1, result.Items.Count);
	}

	[Test]
	public void CollectionShouldNotBeAssigned2()
	{
		var xml = $@"
<CollectionAssignnmentTest xmlns='clr-namespace:MonoTests.Portable.Xaml;assembly=Portable.Xaml_test_net_4_0'>
    <TestClass4/>	
    <TestClass4/>	
</CollectionAssignnmentTest>".UpdateXml();
		var result = (CollectionAssignnmentTest)XamlServices.Parse(xml);

		Assert.False(result.Assigned);
		Assert.AreEqual(2, result.Items.Count);
	}

	[Test]
	public void CollectionShouldBeAssigned()
	{
		var xml = $@"
<CollectionAssignnmentTest xmlns='clr-namespace:MonoTests.Portable.Xaml;assembly=Portable.Xaml_test_net_4_0'
					  	   xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'
						   xmlns:scg='clr-namespace:System.Collections.Generic;assembly=mscorlib'>
	<scg:List x:TypeArguments='TestClass4'>
		<TestClass4/>	
		<TestClass4/>	
	</scg:List>
</CollectionAssignnmentTest>".UpdateXml();
		var result = (CollectionAssignnmentTest)XamlServices.Parse(xml);

		Assert.True(result.Assigned);
		Assert.AreEqual(2, result.Items.Count);
	}
}
```

All of these tests pass on System.Xaml, but the first two fail on Portable.Xaml.
 
Does this demonstrate the problem fully? I can't see any difference between 1 item and >1 item (the first 2 tests).

**Comment by cm4ker** [comment]
Hmm... I miss something. Yea I think this demonstrate the problem fully. Then the we are explictly set type arguments then the collection assign by the xaml-engine. I will update the tests and make some fixes.

**Comment by cwensley** [comment]
Ah yeah, it doesn't make sense to set the property if the value was actually retrieved from the property.  Other than immutable values, which you have accounted for.

It looks like this conflicts with some of the other PR's.. can you rebase so I can merge it in?  Thanks!

**Comment by cm4ker** [comment]
@cwensley I'm newbie in git. How I can reach this? Update the current brunch from develop then add this commit?

**Comment by cwensley** [comment]
@cm4ker no problem. While on the branch, do:
```
git fetch
git rebase origin/master
```
.. then resolve any conflicts, commit, then force push.

**Comment by cm4ker** [comment]
Looks like I'm done. But it was nightmare, first I make a  rebase not with upstream develop and more and more mistakes.... I read all docs about rebase. I check tests shure that it passed after that I make push.

ps (I found uncorrect test while rebasing  public void Write_UnknownType() in the XamlObjectWriterTest.cs)

**Comment by cm4ker** [comment]
@cwensley if I do something wrong. I can create new brunch and transfer my commit by hands.

**Comment by cm4ker** [comment]
Wow. This not a passed. Ok I'll go to resolve this. Git is a complex tool.

**Comment by cwensley** [comment]
Hm, looks like your `origin/master` is probably pointing somewhere else (perhaps avalonia/portable.xaml/master).. 

I think creating a new branch may be best as it's now borked and includes all changes from that branch, not just the collection changes that this PR should include.

**Comment by cwensley** [comment]
> Git is a complex tool.

This is why I use SourceTree.  I can do complex things without having to memorize command line options, and can review changes before pushing.

**Pull request closed without merging**
