### PR TITLE
Re-issuing fix for bug: Escape characters not supported in markup extensions

### PR DESCRIPTION
**Pull request by dominicpease**
Apologies if I violate any rules of etiquette here-- first PR!

### Bug: Escape characters not supported in markup extensions

Per [the XAML spec](https://msdn.microsoft.com/en-us/library/ee200269.aspx), markup extension parsing should respect the backslash as an escape character; any character following a backslash should be consumed as-is and not used to terminate the extension. However, Portable.Xaml (and presumable the underlying Mono version) does not conform to this aspect of the spec.

For instance, given the following:

    {MyExtension6 'Quoted string: \'test\'; Embedded braces: {test\}; Two Backslashes: \\\\'}

...the parser should populate the first positional property with:

    Quoted string test: 'test'; Embedded braces: {test}; Two Backslashes: \\

The existing code truncates the value, because it does a naïve search for the first single quote, treating the escape character as normal text:

    Quoted string test: \

This pull request resolves the bug by adding escape character support to `ParsedMarkupExtensionInfo.cs`. This prevents quoted strings passed to markup extensions from being prematurely terminated due to escaped subquotes or escaped right-braces. It removes escape characters from output where applicable and allows backslash-escaping as well.

Since no existing tests in the test suite covered the broken use cases, I provided new test `Load_CustomExtensionWithEscapeCharacters()` in `XamlXmlReader.cs`, which makes use of the new `CustomExtensionWithEscapeChars.xml` test file. Note that the nature of the test (actually inflating a whole object) differs from the other tests in the file, which mainly look at the XAML nodes read by the reader. This is insufficient, as the error doesn't happen at this stage but when the markup extension is actually parsed. I considered creating a separate file with those, but the test is parallel to the other markup extension tests adjacent to where I inserted the new one.

All the same tests pass as when I cloned the solution, so I assume this did not introduce any other functional changes in the codebase.

Again, this is my first pull request, so any feedback is welcome!

### CODE REVIEW

**Comment by dominicpease** [comment]
I don't know why the "Updating to 0.14.0-alpha" commit (etc) is still hanging around in there. Sorry. Since I don't have any more time to figure out how to undo and redo things, I've just manually undone the changes to AssemblyInfo.cs and committed them. The actual file changes are now what they should be. If you can just pull one specific commit from the PR, 047bbe4 should be the one you want. Alternatively, if you prefer to work with a patch file, [here's one with the changes that fix the bug](https://github.com/cwensley/Portable.Xaml/files/323038/escapechars.zip) but won't pollute any history.

**Comment by cwensley** [comment]
Hey, thanks for the PR!  This looks great.  You might be running into problems because you are merging with the master branch.  All pull requests in this repo go through the develop branch, since master is considered the 'stable' branch.

**Comment by dominicpease** [comment]
OK, I'll try to clean it up once more and resubmit against the development branch. I wasn't sure which to use because there were commits on both side that weren't in the others. (I imagine this is normal, just a factor of me being an OSS neophyte!)

Is there anything else obvious I'm missing? Also, if we merge here, is there a way to push it back up to Mono, or should I do that separately? Thanks for your direction!

**Comment by dominicpease** [comment]
OK, now I really do think I have a clean slate. Closing this and hoping third time's a charm.

**Pull request closed without merging**
