### PR TITLE
Add line info to parse errors, to ease diagnosis and fixing.

### PR DESCRIPTION
**Pull request by mterwoord**

### CODE REVIEW

**Comment by cwensley** [comment]
Hey @mterwoord , thanks for the PR but this breaks many of the tests.  We need to figure out how System.Xaml reports the line info and do it that way.  I think there's some implementation already but you may have to turn it on explicitly.  

Please be sure to test the System.Xaml tests on windows to verify that the behaviour is the same.

**Comment by mterwoord** [comment]
Where can I find the System.Xaml tests?

**Comment by cwensley** [comment]
The .NET/System.Xaml tests can be run using [this](https://github.com/cwensley/Portable.Xaml/blob/develop/src/Test/Portable.Xaml-tests-net_4_5.csproj) project.  You must run the tests on windows otherwise it uses mono's quite broken implementation of System.Xaml.  You can use the NUnit VS addin to run them, or run externally via the NUnit gui.

The Portable.Xaml tests can be run using any of the other test projects.

Ideally we should also have some tests to verify the implementation so it doesn't break in the future.

Hope this helps, and thanks again for helping out!

**Comment by mterwoord** [comment]
Closing, as i'm working ona  different approach.

**Pull request closed without merging**
