### PR TITLE
Fixing line information transfer from XmlReader to the XamlXmlReader

### PR DESCRIPTION
**Pull request by cm4ker**
Hi there! This PR is a reworked https://github.com/cwensley/Portable.Xaml/pull/80 (pulled by @mterwoord, thanks for adding tests and base code!). I finding the cause of failing test. The XamlXmlReader worked that: 
1) Create list of Attributes and Members of instnace by reading through the underlied CompatibleXmlReader -> XmlReader that have correct line and position information.

2) After  analysing all Attr and Members the attributes converted to the members and add it, but the reader not in right position at the right moment.

What I do: I store information from XmlReader in the read moment and then pass it in right moment.

This is PR ready for review.

### CODE REVIEW

**Comment by cwensley** [comment]
Hey @cm4ker, wow you're on a roll!

This looks excellent.  Though would it make sense to combine Pair/MemberInfo and StringPair/AttributeMemberInfo so we don't have multiple types managing the info?

**Comment by cwensley** [comment]
.. or I guess it doesn't matter since they are all structs, so it's not really allocating extra info.. though it is passing extra info through the constructor reducing performance slightly..

**Comment by cm4ker** [comment]
I try to not a break current concept. I don't know how to pass the addition infomation about the current position to the node more elegant in the case then read time and pass time are different. 

Have you any proposals how I can make this better?

Thank you!

**Comment by cm4ker** [comment]
I  change the brunch for this pr and repopen it

**Pull request closed without merging**
