### PR TITLE
Add support for IgnoreDataMemberAttribute

### PR DESCRIPTION
**Pull request by LunicLynx**
## Add support for IgnoreDataMemberAttribute

[MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.ignoredatamemberattribute?view=netcore-3.0)

Fixes part of #144

### CODE REVIEW

**Comment by LunicLynx** [comment]
What needs to be done to get this merged?

**Comment by cwensley** [comment]
Sorry for the late response.  I finally got AppVeyor running again. 

Looks like there's a compile error when compiling the tests for System.Xaml..

**Comment by Aminator** [comment]
@LunicLynx Could you look into fixing this compile error? I would really like to have support for that attribute.

**Comment by cwensley** [comment]
This is now merged in PR #150, and I added some changes.  Namely this is an opt-in feature with `XamlObjectReaderSettings.UseIgnoreDataMemberAttribute` as System.Xaml does not use this attribute.

**Pull request closed without merging**
